src/mastodon-lib.c: fix `gcc-15` build (`bool` collision)
Without the chnage `bitlbee-mastodon` fails the build on `gcc-15` as:

     mastodon-lib.c:2096:28: error: 'bool' cannot be used here
      2096 | static char *yes_or_no(int bool)
           |                            ^~~~

This happens because `gcc-15` switched to `c23` by default which defines
a `bool` as builtin type.

The change avoids use of `bool` as an identifier.